# NUMPY ARRAYS

In [1]:
import numpy as np

### 1D NumPy Arrays

In [2]:
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]

In [4]:
arr = np.array(list)

In [5]:
print(arr*4)

[ 80 108  36  48 124  68  16 200 156 140]


In [7]:
print(np.mean(arr))

24.4


In [8]:
print(np.median(arr))

23.5


In [9]:
print(np.std(arr))

13.828955130450023


In [10]:
print(np.argmin(arr), np.argmax(arr))

6 7


In [12]:
print(f"this is the minimum value: {arr[6]}, this is the maximum value: {arr[7]}")

this is the minimum value: 4, this is the maximum value: 50


In [19]:
print(np.min(arr), np.max(arr)) # values match!

4 50


In [20]:
boolean_index = arr > 20

In [21]:
arr_over_20 = arr[boolean_index]
print(arr_over_20)

[27 31 50 39 35]


### 2D NumPy Arrays

In [22]:
matrix = np.array([
[5, 12, 17, 9],
[8, 21, 14, 3],
[6, 13, 19, 11]
])

In [25]:
print(matrix.shape) # the array has 3 rows and 4 columns

(3, 4)


In [26]:
print(matrix[:, 2])

[17 14 19]


In [27]:
print(matrix[1,:])

[ 8 21 14  3]


In [28]:
print(matrix*2)

[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]


In [30]:
mean_col1 = np.mean(matrix[:, 0])
mean_col2 = np.mean(matrix[:, 1])
mean_col3 = np.mean(matrix[:, 2])
mean_col4 = np.mean(matrix[:, 3])
print(f"The mean of column one is {mean_col1}. The mean of column 2 is {mean_col2}. The mean of column 3 is {mean_col3} and the mean of column 4 is {mean_col4}.")

The mean of column one is 6.333333333333333. The mean of column 2 is 15.333333333333334. The mean of column 3 is 16.666666666666668 and the mean of column 4 is 7.666666666666667.


In [31]:
matrix_mean = np.mean(matrix)
print(f"The overall mean is: {matrix_mean}")

The overall mean is: 11.5


In [32]:
max_row1 = np.max(matrix[0, :])
max_row2 = np.max(matrix[1, :])
max_row3 = np.max(matrix[2, :])

min_col1 = np.min(matrix[:, 0])
min_col2 = np.min(matrix[:, 1])
min_col3 = np.min(matrix[:, 2])
min_col4 = np.min(matrix[:, 3])

print(f"The maximums of each row are {max_row1}, {max_row2}, and {max_row3}. The minimums of each column are {min_col1}, {min_col2}, {min_col3}, and {min_col4}.")

The maximums of each row are 17, 21, and 19. The minimums of each column are 5, 12, 14, and 3.


In [39]:
flattened_matrix = matrix.flatten()
print(flattened_matrix)
# flatten() has turned the matrix into a 1D array with shape 12 for 12 items

[ 5 12 17  9  8 21 14  3  6 13 19 11]


In [40]:
flattened_min_index = np.argmin(flattened_matrix)
flattened_max_index = np.argmax(flattened_matrix)
print(f"Using the flattened array, the minimum is at the {flattened_min_index} index while the maximum is at {flattened_max_index}.")

Using the flattened array, the minimum is at the 7 index while the maximum is at 5.


In [48]:
recover_max_coordinates = np.unravel_index(flattened_max_index, matrix.shape)
recover_min_coordinates = np.unravel_index(flattened_min_index, matrix.shape)
print(f"The row-column coordinates of the minimum is {recover_min_coordinates}, and that of the maximum is {recover_max_coordinates}.")
# correct coordinates but couldn't figure out how to fix/ switch the data type

The row-column coordinates of the minimum is (np.int64(1), np.int64(3)), and that of the maximum is (np.int64(1), np.int64(1)).


In [50]:
above_15 = matrix[matrix > 15]
print(above_15)

[17 21 19]


In [52]:
sorted_row1 = np.sort(matrix[0])
sorted_row2 = np.sort(matrix[1])
sorted_row3 = np.sort(matrix[2])
sorted_matrix = np.array([sorted_row1, sorted_row2, sorted_row3])
print(sorted_matrix)

[[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


### Prime Star Systems

In [53]:
star_mag = np.array([
[2, 3, 5],
[14, 6, 8],
[11, 13, 17],
[7, 10, 13]
])
print(star_mag)

[[ 2  3  5]
 [14  6  8]
 [11 13 17]
 [ 7 10 13]]


In [57]:
def prime_mag(array):
    def check_prime(n):
        if n < 2:
            return False
        for i in range(2, int(n/2) +1 ):
            if n % i == 0:
                return False # numpy doesn't have a prime function so in theory this tests all numbers from 2 to half of the number as an integer plus one since even if it is closer to the higher integer it rounds down. 
        else: 
            return True

    mask = [any(check_prime(x) for x in row) for row in array] # learned about masked arrays on numpy website to have booleans "interact" with data (so the true/false statements result in a new array)
    return array[mask] 
print(prime_mag(star_mag))

[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


### Let's Play Checkers!

In [62]:
checkerboard = np.zeros((8,8))
print(checkerboard)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [63]:
for i in range(checkerboard.shape[0]):
    if i % 2 == 0:
        for j in range(checkerboard.shape[1]):
            if j % 2 == 0:
                checkerboard[i,j] = 1
checkerboard

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [64]:
for i in range(checkerboard.shape[0]):
    if i % 2 == 1:
        for j in range(checkerboard.shape[1]):
            if j % 2 == 1:
                checkerboard[i,j] = 1
checkerboard

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [65]:
def reverse_checkerboard(array):
    return 1 - array
print(reverse_checkerboard(checkerboard))

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


### The Expanding Universe

In [68]:
universe = np.array(['galaxy', 'clusters'])
def expansion(array, n):
    expanding_space = " " * n
    return np.array([expanding_space.join(string) for string in array])
print(expansion(universe, 4))

['g    a    l    a    x    y' 'c    l    u    s    t    e    r    s']


### Second-Brightest Star

In [73]:
np.random.seed(42) # the answer to the universe because why not
stars = np.random.randint(500, 2000, (5,5)) # random integers from 500 to 2000 using the random seed specified in a 5x5 array
# use np.sort from the previous problem and negative indexing to get second largest for a row of any length! 
stars

array([[1626, 1959, 1360, 1794, 1630],
       [1595, 1544,  621,  966, 1738],
       [ 830, 1982,  587, 1896, 1623],
       [1371,  630, 1832, 1269,  843],
       [1937, 1305,  885, 1715, 1455]], dtype=int32)

In [76]:
def second_dimmest(array):
    new_array = []
    for row in array:
        sorted_row = np.sort(row)
        new_array.append(sorted_row[-2]) # adds the second largest value of the row to the new array
    return np.array(new_array)

print(second_dimmest(stars))

[1794 1595 1896 1371 1715]
